CodeLangs = {
    '.c': 'C',
    '.py': 'Python',
    '.java': 'Java',
    '.cpp': 'C++',
    '.js': 'JavaScript',
    '.cs': 'C#',
    '.html': 'HTML',
    '.php': 'PHP',
    '.go': 'Go',
    '.swift': 'Swift',
    '.pl': 'Perl',
    '.sql': 'SQL',
    '.rb': 'Ruby',
    '.vb': 'Visual Basic',
    '.dart': 'Dart',
    '.scala': 'Scala',
    '.asm': 'Assembly',
    '.pas': 'Pascal',
    '.ksh': 'Korn Shell',
    '.clj': 'Clojure',
    '.f90': 'Fortran',
    '.vbscript': 'VBScript',
    '.coffee': 'CoffeeScript',
    '.erl': 'Erlang',
    '.hs': 'Haskell',
    '.cl': 'OpenCL',
    '.el': 'Emacs Lisp',
    '.lua': 'Lua',
    '.prolog': 'Prolog',
    '.ml': 'OCaml',
    '.r': 'R',
    '.awk': 'Awk',
    '.rs': 'Rust',
    '.st': 'Smalltalk',
    '.scm': 'Scheme',
    '.pli': 'PL/I',
    '.nim': 'Nim',
    '.lisp': 'Common Lisp',
    '.ts': 'TypeScript',
    '.julia': 'Julia',
    '.json': 'JSON',
    '.xml': "XML",
    ".yaml": "YAML",
    ".tsql": "Transact-SQL"
  }